export const SHOW_SURVEYS = 'SHOW_SURVEYS';
export const DELETE_SURVEY = "DELETE_SURVEY";
export const ADD_QUESTION = 'ADD_QUESTION';
export const CHANGE_QUESTION_TITLE = 'CHANGE_QUESTION_TITLE';
export const PREVIEW_SURVEY = 'PREVIEW_SURVEY';
export const SUBMET_SURVEY = "SUBMET_SURVEY";