export const SHOW_SURVEYS = 'SHOW_SURVEYS';
export const FETCH_SURVEYS_FAILED = "FETCH_SURVEYS_FAILED";
export const ADD_QUESTION = 'ADD_QUESTION';
export const CHANGE_QUESTION_TITLE = 'CHANGE_QUESTION_TITLE';
